name: Docker version
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check docker version
        run: docker --version
      - name: Git Version
        run: git --version
      - name: Github cli Version
        run: gh --version
      - name: Github Clone
        run: gh repo clone KPMG-UK/terraform-az-blob-clamav
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_PWD: ${{ secrets.GH_PWD }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}


