name: Docker version
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check docker version
        run: docker --version
      - name: Git Version
        run: git --version
      - name: Github cli Version
        run: gh --version
      - name: Github cli Version
        run: gh issue create --title "My new issue" --body "Here are more details."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

